### PR TITLE
Fix transpilation options in noise model

### PR DESCRIPTION
**Pull request by jyu00**
### Summary

`coupling_map` and `basis_gates` should be transpilation options, not run options. 

### Details and comments
Fixes #

### CODE REVIEW

**Review by kt474 — COMMENTED** [review]
The options in `test_noise_model` will have to be updated - [here](https://github.com/Qiskit/qiskit-ibm-runtime/blob/a3ee39156edf5342ec505a80f326032c86aa8c1f/test/integration/test_options.py#L45) 

Something like 
```python
options = Options(
      simulator={
          "noise_model": noise_model,
          "seed_simulator": 42,
      },
      transpilation=TranspilationOptions(
          basis_gates=fake_backend.configuration().basis_gates,
          coupling_map=fake_backend.configuration().basis_gates,
      ),
  )
```

**Comment by jyu00** [comment]
> The options in `test_noise_model` will have to be updated too - [here](https://github.com/Qiskit/qiskit-ibm-runtime/blob/a3ee39156edf5342ec505a80f326032c86aa8c1f/test/integration/test_options.py#L45)
> 
> Something like
> 
> ```python
> options = Options(
>       simulator={
>           "noise_model": noise_model,
>           "seed_simulator": 42,
>       },
>       transpilation=TranspilationOptions(
>           basis_gates=fake_backend.configuration().basis_gates,
>           coupling_map=fake_backend.configuration().basis_gates,
>       ),
>   )
> ```

My thinking is that `basis_gates` and `coupling_map` will remain under `simulator`, since they only apply to simulators. But under the cover they'll be set as transpilation options to the primitives.

**Comment by kt474** [comment]
> My thinking is that `basis_gates` and `coupling_map` will remain under `simulator`, since they only apply to simulators. But under the cover they'll be set as transpilation options to the primitives.

Ah ok makes sense - `test_noise_model` fails on this branch with the following error so I wasn't sure:

```python
2022-10-12T15:52:11.771096821Z Message: 'Error executing program job cd3e591h5tg0g0d26uk0'
2022-10-12T15:52:11.771122320Z Arguments: (KeyError('coupling_map'),)
2022-10-12T15:52:11.782135926Z Traceback (most recent call last):
2022-10-12T15:52:11.782175285Z   File "/code/program_starter.py", line 57, in <module>
2022-10-12T15:52:11.782446433Z     starter.execute()
2022-10-12T15:52:11.782471855Z   File "/provider/programruntime/program_starter_wrapper.py", line 99, in execute
2022-10-12T15:52:11.782575924Z     raise ex
2022-10-12T15:52:11.782614087Z   File "/provider/programruntime/program_starter_wrapper.py", line 89, in execute
2022-10-12T15:52:11.782849867Z     final_result = self.main(backend, self.messenger, **self.user_params)
2022-10-12T15:52:11.782872919Z   File "/code/program.py", line 686, in main
2022-10-12T15:52:11.783394326Z     transpiled_circuits = sampler.transpiled_circuits
2022-10-12T15:52:11.783417380Z   File "/code/program.py", line 139, in transpiled_circuits
2022-10-12T15:52:11.783461439Z     transpiled_circuits = self._transpile(circuits=self._circuit_cache.raw_circuits)
2022-10-12T15:52:11.783507948Z   File "/code/program.py", line 155, in _transpile
2022-10-12T15:52:11.783857092Z     transpile(
2022-10-12T15:52:11.783879950Z   File "/opt/app-root/lib64/python3.8/site-packages/qiskit/compiler/transpiler.py", line 318, in transpile
2022-10-12T15:52:11.784207168Z     cmap_conf = [shared_args["coupling_map"]] * len(circuits)
2022-10-12T15:52:11.784230718Z KeyError: 'coupling_map'
```

**Review by kt474 — APPROVED** [review]

**Comment by jyu00** [comment]
> Ah ok makes sense - `test_noise_model` fails on this branch with the following error so I wasn't sure:

Oops I passed `basis_gates` to coupling_map. Fixed in [5dffdfa](https://github.com/Qiskit/qiskit-ibm-runtime/pull/573/commits/5dffdfa0ecd85e06e66e3ef82a97234581b35f64)

**Pull request merged**
