### PR TITLE
Add missing API docs [wip]

### PR DESCRIPTION
**Pull request by beckykd**
### Summary
The documentation for some Runtime API modules is not showing up correctly

### Details and comments
Fixes # 
This is related to https://github.com/Qiskit/documentation/issues/238

### CODE REVIEW

**Comment by Eric-Arellano** [comment]
I'll help get this green and add back Kevin and Jessie when green. Feel free to unsubscribe in the meantime.

**Comment by kaelynj** [comment]
@Eric-Arellano, I have some progress on this done now, but I can't push to this repo.  How can I get added to the contributor list?

**Comment by Eric-Arellano** [comment]
I recommend instead creating a new PR and make sure it includes Becky's original commit so that she gets credit.

**Comment by Eric-Arellano** [comment]
Superseded by https://github.com/Qiskit/qiskit-ibm-runtime/pull/1343

**Pull request closed without merging**
