### PR TITLE
Cleanup tox configuration and usage

### PR DESCRIPTION
**Pull request by daka1510**
### Summary
As of today the CI uses `tox` for building the documentation (via `tox -edocs`) but not for anything else. The configuration file, `tox.ini`,  contains invalid and outdated sections. This PR aims to improve consistency.

Changes
- Updated `tox.ini` configuration
- Updated CI to use `tox` consistently

I did not change or remove the `Makefile` as some developers may prefer to continue using it as primary interface (e.g. because they want to stay in control over venv management).

### Details and comments
Fixes https://github.com/Qiskit/qiskit-ibm-runtime/issues/25

### CODE REVIEW

**Comment by mtreinish** [comment]
You do realize that tox is the standard entry point for testing used in the rest of qiskit? (it's also documented in the overall project contributing guide: https://qiskit.org/documentation/contributing_to_qiskit.html)  It's used pretty consistently by all the other projects to automate venv isolation, installation, and testing for development and to provide a consistent environment between ci and local development. The testing for the ibm packages has always been non standard but removing support for the standard entrypoint seems like the wrong call. It should be trivial to fix the issues with config whether it's used in ci or not.

**Comment by daka1510** [comment]
Thanks for raising these concerns and sharing your perspective, @mtreinish. I agree that it's equally trivial to keep support for `tox -edocs` and instead remove the outdated configuration sections in `tox.ini`. 

For `qiskit-ibm-runtime`, we use `tox` for building the documentation and `make` for all other tasks developers and CI systems run. This appears inconsistent to me as well and took me - as new contributor - extra efforts to learn and understand.

As you raised a broader concern ("testing for the ibm packages has always been non standard") and I lack the required project history, I'd also like to hear the perspective from @jyu00 and @rathishcholarajan before I update my PR in one or the other direction.

**Comment by daka1510** [comment]
Any thoughts or recommendations, @mtreinish?

**Comment by daka1510** [comment]
Not a priority at this time. Can easily be reopened and replicated when conflicts are resolved. Closing.

**Pull request closed without merging**
