### PR TITLE
Added deprecation warning when using qiskitrc file

### PR DESCRIPTION
**Pull request by merav-aharoni**
### Summary
Deprecation of qiskitrc file before complete removal.

### Details and comments
 See review comment in #1023

### CODE REVIEW

**Comment by merav-aharoni** [comment]
When I tried to use a `DeprecationWarning` rather than a simple `warning`, I get a failure on `test_enable_account_by_qiskitrc`. As far as I understand, the reason is that in the tests, deprecation messages are treated as errors. I realize this should only hold for deprecation messages from `qiskit`. However, when I comment out the line 
```
        warnings.filterwarnings("error", category=DeprecationWarning, module="qiskit")

```
in `ibm_test_case.py`, the deprecation message does not cause a failure.
Any suggestions?

**Comment by kt474** [comment]
https://github.com/Qiskit/qiskit-ibm-runtime/blob/d23fa543ef60c194ddce223b50740894a287dd22/test/ibm_test_case.py#L51

I see, I shouldn't have used `module="qiskit"` here since that would match all modules starting with qiskit, which includes qiskit_ibm_runtime. Instead, regex should be used and we can replace it with `module=r'^qiskit$'`

**Comment by merav-aharoni** [comment]
Is this the correct version number? period for removal?

**Comment by merav-aharoni** [comment]
@kt474 - when I run the test `test_enable_account_by_qiskitrc` with the deprecation warning, the test passes, but I get the following messages, about a file not being closed:
```
OK
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/tmppaexvbyw' mode='w+' encoding='UTF-8'>
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/tmpek7vt_qi' mode='w+' encoding='UTF-8'>
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/tmp3vt623pj' mode='w+' encoding='UTF-8'>
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/tmpz0t4dfjo' mode='w+' encoding='UTF-8'>
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/tmprz2cq7y4' mode='w+' encoding='UTF-8'>
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/tmp35mtw27q' mode='w+' encoding='UTF-8'>
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/tmpez_a_afy' mode='w+' encoding='UTF-8'>
```
Any idea what is causing this?

**Comment by kt474** [comment]
> Any idea what is causing this?

Is it coming from that specific test? I don't see those errors when I run the tests locally and I can't find them in the github actions logs

**Comment by merav-aharoni** [comment]
> > Any idea what is causing this?
> 
> Is it coming from that specific test? I don't see those errors when I run the tests locally and I can't find them in the github actions logs

I get these messages when I run `test_enable_account_by_qiskitrc` locally. If you aren't getting them, maybe it is a problem in my environment, and then we are okay.

**Review by kt474 — APPROVED** [review]

**Pull request merged**
