### PR TITLE
Split sessions topic into two

### LINKED ISSUE #696: Add how-to on retrieving jobs
**What is the expected feature or enhancement?**

At one point there was documentation on how to retrieve a previously submitted job, its results and parameters used. I can't seem to find that anywhere now. 

**Acceptance criteria**

Add a `Retrieve a previous job` section under `How to` that explains how to retrieve a previously submitted job, its results and parameters used.

### PR DESCRIPTION
**Pull request by beckykd**
closes #696 

-->

### Details and comments
Fixes #

### CODE REVIEW

**Comment by jyu00** [comment]
I think we can use this opportunity to change the wording a bit. Something like

```
After submitting your job, a job instance is returned. This job instance can be used to check job status (by calling `job.status()`) as well as retrieving its results (by calling `job.result()`). Job results are available after the job completes, and `job.result()` is a blocking call until the job completes.

Calling `job.job_id()` returns the job ID, which uniquely identifies that particular job. You can call `service.job(<job ID>)` to retrieve a job you previously submitted. Since the job ID is required in this call, it is recommended that you save the IDs of jobs you may want to retrieve later. If you don't have the job ID, or if you want to retrieve multiple jobs at once, you can call `service.jobs()` with optional filters instead. 

Jobs from retired systems can be retrieved in the same way. 

Jobs are also listed on the Jobs page for your quantum service channel:

- If you are using the IBM Cloud channel, from the IBM Cloud console quantum [Instances page](https://cloud.ibm.com/quantum/instances), click the name of your instance, then click the Jobs tab. To see the status of your job, click the refresh arrow in the upper right corner.
- If you are using the IBM Quantum channel, in IBM Quantum platform, open the [Jobs page](https://quantum-computing.ibm.com/jobs).
```

**Comment by beckykd** [comment]
> I think we can use this opportunity to change the wording a bit. Something like
> 
> ```
> After submitting your job, a job instance is returned. This job instance can be used to check job status (by calling `job.status()`) as well as retrieving its results (by calling `job.result()`). Job results are available after the job completes, and `job.result()` is a blocking call until the job completes.
> 
> Calling `job.job_id()` returns the job ID, which uniquely identifies that particular job. You can call `service.job(<job ID>)` to retrieve a job you previously submitted. Since the job ID is required in this call, it is recommended that you save the IDs of jobs you may want to retrieve later. If you don't have the job ID, or if you want to retrieve multiple jobs at once, you can call `service.jobs()` with optional filters instead. 
> 
> Jobs from retired systems can be retrieved in the same way. 
> 
> Jobs are also listed on the Jobs page for your quantum service channel:
> 
> - If you are using the IBM Cloud channel, from the IBM Cloud console quantum [Instances page](https://cloud.ibm.com/quantum/instances), click the name of your instance, then click the Jobs tab. To see the status of your job, click the refresh arrow in the upper right corner.
> - If you are using the IBM Quantum channel, in IBM Quantum platform, open the [Jobs page](https://quantum-computing.ibm.com/jobs).
> ```

I was looking for the API to link to for more information for service.jobs.  What I found was QiskitRuntimeService.jobs() Is that what we want?  https://qiskit.org/documentation/partners/qiskit_ibm_runtime/stubs/qiskit_ibm_runtime.QiskitRuntimeService.jobs.html

**Comment by jyu00** [comment]
> I was looking for the API to link to for more information for service.jobs. What I found was QiskitRuntimeService.jobs() Is that what we want? https://qiskit.org/documentation/partners/qiskit_ibm_runtime/stubs/qiskit_ibm_runtime.QiskitRuntimeService.jobs.html

Yup, `job()` is for a retrieving a single job and `jobs()` for multiple.

**Comment by beckykd** [comment]
Updated, @jyu00 . Could you take a look?

**Review by jyu00 — APPROVED** [review]
A small nit, but otherwise LGTM. And good job calling out this only retrieves runtime jobs!

**Pull request merged**
