### PR TITLE
Serialize numpy arrays with object types 

### PR DESCRIPTION
**Pull request by kt474**
### Details and comments
Fixes https://github.com/Qiskit-Partners/qiskit-ibm/issues/74

### CODE REVIEW

**Review by daka1510 — APPROVED** [review]
I'm not very familiar with the background on how encoding/deocing works here but based on what I read in the referenced issue and what I see in this PR it looks good :). Guess a secondary reviewer helps to gain more confidence.

**Comment by daka1510** [comment]
@rathishcholarajan though it looks good to me: can you take a quick look if we can integrate it?

**Review by rathishcholarajan — CHANGES_REQUESTED** [review]
@kt474 Looks good. Could you update cloud-production URL to https://cloud.ibm.com in your fork to get rid of these errors https://github.com/kt474/qiskit-ibm-runtime/runs/5094722869?check_suite_focus=true#step:5:1029 and we can see if all integration tests pass before merging this?

**Comment by daka1510** [comment]
@kt474 the integration test jobs of the CI runs on your fork are still failing due to configuration issues
https://github.com/kt474/qiskit-ibm-runtime/actions/workflows/ci.yml?query=branch%3Ajob-results-stream

Can you check again? Feel free to reach out if you need help. More details are also available at https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/CONTRIBUTING.md#configuration

**Review by rathishcholarajan — CHANGES_REQUESTED** [review]
@kt474 Could you please resolve merge conflicts?

**Review by rathishcholarajan — APPROVED** [review]
LGTM!

**Comment by rathishcholarajan** [comment]
@kt474 Could you please backport this as well to qiskit-ibmq-provider?

**Pull request merged**
