### PR TITLE
Add provider compatibility to the runtime service

### PR DESCRIPTION
**Pull request by renier**
### Summary

Adds provider compatibility to the runtime service. This allows us to pass the
runtime service to those algorithm classes that expect a base provider to call
`provider.runtime.run(...)` on, without needing upstream changes.

### CODE REVIEW

**Comment by rathishcholarajan** [comment]
@renier Even though this looks harmless to merge, it was done from the point of view of fixing a bug. We need to think about this a bit more as part of a larger Epic.

Also usually when contributing to this repo it is recommended to fork this repo, work on a branch and then open a PR. That way PR builds won't run all integration tests and fail sometimes, but just the unit tests, which are enough to merge. People usually add their personal environment secrets to their fork as explained in the contribution guidelines and that way we know if integration tests pass on your fork, before merging.

**Comment by renier** [comment]
> @renier Even though this looks harmless to merge, it was done from the point of view of fixing a bug. We need to think about this a bit more as part of a larger Epic.

Yes, let's take time to discuss this first.

> Also usually when contributing to this repo it is recommended to fork this repo, work on a branch and then open a PR. That way PR builds won't run all integration tests and fail sometimes, but just the unit tests, which are enough to merge. People usually add their personal environment secrets to their fork as explained in the contribution guidelines and that way we know if integration tests pass on your fork, before merging.

Ok, I admit I didn't read the guidelines. Will do that in the future.

**Comment by renier** [comment]
@stefan-woerner any objections to this?

**Comment by renier** [comment]
@kt474 if you have no objections, please merge.

**Review by kt474 — APPROVED** [review]

**Pull request merged**
