### PR TITLE
Bug fix in binding parameters of composed circuit

### LINKED ISSUE #809: Circuit parameters can't be bound by Runtime Primitives
**Describe the bug**
Runtime Estimator fails when a complex circuit that is made of instructions created from other circuit is executed. The same circuit runs perfectly well on the reference primitives locally. The script below reproduces the problem. It may look artificial, but a lot of code has been removed to make the script shorter. I do believe the same problem will occur with Sampler.  

**Steps to reproduce**
Add a `TOKEN` definition to the script and run it.
```python
import numpy as np
from qiskit import QuantumCircuit
from qiskit.circuit import ParameterVector
from qiskit.primitives import Estimator
from qiskit.quantum_info import Pauli
from qiskit_ibm_runtime import QiskitRuntimeService, Session, Estimator as RuntimeEstimator


def cloud_execute(qc):
    observable = Pauli("Z" * qc.num_qubits)

    service = QiskitRuntimeService(channel="ibm_quantum", token=TOKEN)
    backend_name = "ibmq_qasm_simulator"
    with Session(service=service, backend=backend_name) as session:
        estimator = RuntimeEstimator(session=session)
        result = estimator.run(qc, observable, np.random.random(qc.num_parameters)).result()
        print(result)


def local_execute(qc):
    observable = Pauli("Z" * qc.num_qubits)
    estimator = Estimator()
    result = estimator.run(qc, observable, np.random.random(qc.num_parameters)).result()
    print(result)


def create_layer(num_qubits, params):
    qc = QuantumCircuit(num_qubits, name="L")

    param_index = 0
    for qubit1 in range(0, num_qubits - 1, 2):
        qubit2 = qubit1 + 1
        unit_params = params[param_index: param_index + 1]
        add_unit(qc, qubit1, qubit2, unit_params)
        param_index += 1

    return qc.to_instruction()


def add_unit(qc: QuantumCircuit, qubit1, qubit2, params):
    u = QuantumCircuit(2, name="U")
    u.rz(params[0], 0)

    qc.compose(u.to_instruction(), [qubit1, qubit2], inplace=True)


num_qubits = 4
qc = QuantumCircuit(num_qubits)

num_params = 2
params = ParameterVector("u", num_params)
layer = create_layer(num_qubits, params)

qc.compose(layer, list(range(num_qubits)), inplace=True)

print(qc.decompose(reps=2))

local_execute(qc)
cloud_execute(qc)
```

Exception is raised `qiskit.circuit.exceptions.CircuitError: \'Cannot bind parameters (u[1]) not present in the circuit.\'`

Full log:
```
Traceback (most recent call last):
  File "... __decompose_bug.py", line 61, in <module>
    cloud_execute(qc)
  File "... __decompose_bug.py", line 18, in cloud_execute
    result = estimator.run(qc, observable, np.random.random(qc.num_parameters)).result()
  File "... lib/python3.8/site-packages/qiskit_ibm_runtime/runtime_job.py", line 226, in result
    raise RuntimeJobFailureError(
qiskit_ibm_runtime.exceptions.RuntimeJobFailureError: 'Unable to retrieve job result. Job cgv6cgj3sd207kpt424g has failed:\nTraceback (most recent call last):\n2023-04-18T09:43:44.024738294Z   File "/provider/server/main.py", line 90, in execute_program\n2023-04-18T09:43:44.024757792Z     starter.execute()\n2023-04-18T09:43:44.024778195Z   File "/provider/programruntime/program_starter_wrapper.py", line 97, in execute\n2023-04-18T09:43:44.024797212Z     raise ex\n2023-04-18T09:43:44.024815487Z   File "/provider/programruntime/program_starter_wrapper.py", line 84, in execute\n2023-04-18T09:43:44.024832275Z     final_result = self.main(backend, self.messenger, **self.user_params)\n2023-04-18T09:43:44.024849954Z   File "/code/program.py", line 1464, in main\n2023-04-18T09:43:44.024867719Z     result = estimator.run(\n2023-04-18T09:43:44.024885527Z   File "/code/program.py", line 270, in run\n2023-04-18T09:43:44.024904502Z     bound_circuits = [\n2023-04-18T09:43:44.024923817Z   File "/code/program.py", line 273, in <listcomp>\n2023-04-18T09:43:44.024940911Z     else transpiled_circuits[circuit_index].bind_parameters(p)\n2023-04-18T09:43:44.024959235Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/circuit/quantumcircuit.py", line 2735, in bind_parameters\n2023-04-18T09:43:44.024977216Z     return self.assign_parameters(values)\n2023-04-18T09:43:44.024993295Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/circuit/quantumcircuit.py", line 2687, in assign_parameters\n2023-04-18T09:43:44.025027333Z     raise CircuitError(\n2023-04-18T09:43:44.025043583Z qiskit.circuit.exceptions.CircuitError: \'Cannot bind parameters (u[1]) not present in the circuit.\'\n2023-04-18T09:43:44.071122732Z /pod-data/ CLOSE_WRITE,CLOSE terminated\n2023-04-18T09:43:44.077314378Z Termination marker file found. Kill process (7).\n'
```

**Expected behavior**
No exception is thrown

**Suggested solutions**
There's a workaround. Replace  `cloud_execute(qc)` with `cloud_execute(qc.decompose(reps=3)` and the problem is solved, but it is inconvenient.

**Additional Information**

- **qiskit-ibm-runtime version**: 0.9.3
- **Python version**: 3.8
- **Operating system**: MacOS

### PR DESCRIPTION
**Pull request by merav-aharoni**
### Details and comments
Fixes #809

### CODE REVIEW

**Comment by merav-aharoni** [comment]
@kt474 - please have a look at this PR and related issue, although it is still a draft. The purpose of this PR is to fix the bug in #809. This indeed fixes the bug, however, I am not sure where is the best place to put this fix. I saw that you removed a `decompose` in PR #780. This is probably related. However, if I try to insert a `decompose` where it was removed, it causes a few tests to fail.

**Comment by merav-aharoni** [comment]
When I add  `obj.decompose(reps=2)` in `qiskit_ibm_runtime/utils/json.py`, the test `test_coder_operators` fails, probably because it fails in comparing input to output, syntactically.
Please advise whether to add back the `decompose` and where this should be added, or if you have any other idea. I don't think this harms performance, because if the circuit is already decomposed to basis gates, it will do nothing. @jyu00 , @kt474 - your inputs will be appreciated .

**Comment by kt474** [comment]
We removed the decompose in #780 because it was originally added as a bug fix but has been fixed on the terra side. I'm not sure what the best fix for #815 would be - thoughts @jyu00? Should this be fixed on our side?

**Comment by kt474** [comment]
Closing for now, this will be fixed on the primitives side - the issue is https://github.com/Qiskit/qiskit-ibm-runtime/issues/809 for reference

**Pull request closed without merging**
