### PR TITLE
Bump to qiskit 1.1

### LINKED ISSUE #1631: Explore possible regression in local simulation performance
**Describe the bug**

A user has noticed a dramatic slowdown in SamplerV2 with FakeSherbrooke:

A demo of ~150 4-qubit circuits has gone from taking a few seconds to over 3 minutes on their machine.
Switching to 5-qubit FakeManila speeds this back up.

Multi-threading things taking a long time in a quick timing profile. Transpiler or aer related?

**Steps to reproduce**

@caleb-johnson may be able to produce one. Otherwise, try something as above.

**Expected behavior**

Small circuits on a large device are just as fast as those same circuits on a small device.

### LINKED ISSUE #1690: Bump to `qiskit>=1.1` dependency
**What is the expected feature or enhancement?**

That the minimum `qiskit` version depended on by this library is 1.1.

**Acceptance criteria**

The requirements are set to `qiskit>=1.1` and tests pass.

### LINKED ISSUE #1691: Job results should be cached once job.result() is called
**What is the expected feature or enhancement?**

Getting job results has to query the API each time `job.result()` is called.  This makes code very slow, and should not have to be done more than once.  Results used to be cached, and should be again.

**Acceptance criteria**
Job results are cached

### LINKED ISSUE #1702: Start using `Backend*V2` qiskit and other qiskit objects directly
**What is the expected feature or enhancement?**

Presently they are duplicated because they were not available in the 1.0 release of qiskit. Once #1690 is closed, we can import them directly.

**Acceptance criteria**

 - Use `SamplerPubResult` instead of `PubResult` for the sampler
 - Use `Backend*V2` implementations from qiskit

### PR DESCRIPTION
**Pull request by t-imamichi**
### Summary

Bump to Qiskit 1.1 and replace Backend Primitives V2 with those of Qiskit 1.1

TODO:  We need to take a benchmark using the local mode just in case

### Details and comments

Fixes #1631
Fixes #1690
Fixes #1702 
Closes #1678

### CODE REVIEW

**Comment by ihincks** [comment]
In order to fully close #1690, we'll need to do things like stop using make_data_bin and _FIELDS. We could also descope that issue, open a new one, and make those changes in a different PR.

**Comment by kt474** [comment]
> Thank you for pointing out them, Ian. I should have made a PR carefully. I will take a look at those items and identify whether I can include them in this PR or I need a separate PR.

Let me know if I can help with some of the work that needs to be split out into a separate PR

**Comment by ihincks** [comment]
I think it will be cleanest if we have 1) this PR, 2) a PR for DataBin access (_FIELDS -> keys() etc), 3) stop using make_data_bin (possible encoder changes).

**Comment by ihincks** [comment]
I've de-scoped #1690 and added #1702, #1703, #1704. 

This PR now closes #1690 and #1702 (as well as the other two listed at the top).

@kt474 all of these can be listed in this sprint, so please feel free to take either or both of the last ones, if you'd like :)

**Comment by t-imamichi** [comment]
Thank you for reorganizing issues. I updated the description to align them. I think this PR should focus on #1702.
I will work on the other items as separate PRs.

**Review by ihincks — APPROVED** [review]
These changes look correct to me, thank you.

**Pull request merged**
