### PR TITLE
Retrieve interim results from runtime jobs

### PR DESCRIPTION
**Pull request by kt474**
### Summary

Ported from https://github.com/Qiskit-Partners/qiskit-ibm/pull/162

### CODE REVIEW

**Review by rathishcholarajan — CHANGES_REQUESTED** [review]
@kt474 Please fix lint issues.

**Comment by kt474** [comment]
on hold - waiting for api team to fix the issue with returning duplicate results

**Comment by kt474** [comment]
> @kt474 could you please run a sample program and check if we are getting duplicate results anymore?

Just tested on both staging and prod, still getting duplicate results

**Comment by rathishcholarajan** [comment]
> > @kt474 could you please run a sample program and check if we are getting duplicate results anymore?
> 
> Just tested on both staging and prod, still getting duplicate results

Renier says he is not seeing the duplicate results when he runs sample-program from API directly. Could you try running some other program like a basic circuit-runner program from qiskit-runtime tutorials to see if there is any duplication?

Renier (Quote):
```
I tried to reproduce this but could not,

[
  "{\"iteration\": 3, \"counts\": {\"01010\": 12, \"11010\": 35, \"00110\": 54, \"11110\": 527, \"00010\": 6, \"10110\": 242, \"10010\": 23, \"01110\": 125}}",
  "{\"iteration\": 2, \"counts\": {\"10000\": 4, \"10010\": 1020}}",
  "{\"iteration\": 1, \"counts\": {\"01000\": 512, \"00000\": 512}}",
  "{\"iteration\": 0, \"counts\": {\"00010\": 521, \"00000\": 503}}"
] 
That was using the API directly. You might want to check the provider code to make sure it is not introducing this itself.
```

**Comment by kt474** [comment]
tested with sample-vqe program, still getting duplicate interim results - I don't believe it's an issue with the code here as testing the endpoint directly [here](https://runtime-us-east.quantum-computing.ibm.com/openapi/#/Jobs/get_interim_results_jid) gives the same result

**Comment by rathishcholarajan** [comment]
@kt474 Could you try running a sample-program from the swagger UI https://runtime-us-east.quantum-computing.ibm.com/openapi/#/Jobs/create_job and then check interim results API?

**Comment by kt474** [comment]
> @kt474 Could you try running a sample-program from the swagger UI https://runtime-us-east.quantum-computing.ibm.com/openapi/#/Jobs/create_job and then check interim results API?

Getting the same result when running from the swagger UI 

```
[
  "{\"iteration\": 0, \"counts\": {\"00010\": 1024}}",
  "{\"iteration\": 0, \"counts\": {\"00010\": 1024}}",
  "{\"iteration\": 0, \"counts\": {\"00010\": 1024}}"
]
```

**Review by rathishcholarajan — APPROVED** [review]
Looks good @kt474! The API is fixed now.

**Pull request merged**
