### PR TITLE
Add CHSH with Estimator tutorial

### PR DESCRIPTION
**Pull request by HuangJunye**
### Summary

This PR adds a new tutorial: CHSH with Estimator tutorial.

QPE with Sampler tutorial is in a separate PR #404 

Co-authored-by: @adcorcol
Co-authored-by: @beckykd

### Details and comments
Fixes #

### CODE REVIEW

**Comment by kt474** [comment]
@HuangJunye Same question - is this good to go?

**Comment by HuangJunye** [comment]
@kt474 I need to incorporate some changes from the feedback of the user testing session. After that it should be good to go.

**Comment by HuangJunye** [comment]
@tmittal947 Can you please sign the CLA as you are a co-author of the PR.

**Comment by HuangJunye** [comment]
@kt474 This PR should be good to be merged. Only thing I need to address from the user testing is to change the plot colors. @JulesMurphy can the designers team provide color choices? I personally this won't be a blocking issue for merging. We can always change the color in a separate PR.

**Review by kt474 — APPROVED** [review]

**Comment by tmittal947** [comment]
@HuangJunye Done

**Pull request merged**
