### PR TITLE
Prepare release 0.7.0rc1

### PR DESCRIPTION
**Pull request by kt474**
### Summary

Move all reno to 0.7 folder 

### Details and comments
Fixes #

### CODE REVIEW

**Comment by jyu00** [comment]
Can we wait for https://github.com/Qiskit/qiskit-ibm-runtime/issues/474 before doing the release? Since the fix will be a breaking change (which also means fix should wait for the workshop lol).

**Comment by kt474** [comment]
> Can we wait for #474 before doing the release? Since the fix will be a breaking change (which also means fix should wait for the workshop lol).

Sure, I can work on that - fyi @renier

**Comment by renier** [comment]
We can do multiple pre-releases as needed. Prereleases can break the interface still. Do we really need to wait for #474 ?

**Comment by jyu00** [comment]
> We can do multiple pre-releases as needed

Sure, but it does take time (even if none significant). I don't see any benefit of doing a pre-release now, but it's up to you.

**Comment by renier** [comment]
@kt474 we promised one this week, so let's not hold up.

**Review by renier — APPROVED** [review]

**Pull request merged**
