### PR TITLE
Remove importing PauliSumOp, which is deprecated

### PR DESCRIPTION
**Pull request by 1ucian0**
Partial fix to https://github.com/Qiskit/qiskit-ibm-runtime/issues/1057

Skip importing `PauliSumOp`, which is only used for type hinting.

### CODE REVIEW

**Review by ElePT — COMMENTED** [review]
A couple of comments:
1. As far as I know, this typehint was left to maintain consistency with the base classes, which still preserve the `PauliSumOp` input type. Shouldn't this change be coordinated with the base primitives?? (for which, I believe, the plan is to keep the opflow typehint until opflow is removed)
2. There are still a few uses of `PauliSumOp` in the code (lines 125, 161)

**Comment by 1ucian0** [comment]
> 1. As far as I know, this typehint was left to maintain consistency with the base classes, which still preserve the `PauliSumOp` input type. Shouldn't this change be coordinated with the base primitives?? (for which, I believe, the plan is to keep the opflow typehint until opflow is removed)

You believe is correct. As a typehint still works, but does not import it at runtime.

> 2. There are still a few uses of `PauliSumOp` in the code (lines 125, 161)

Also typehints, right?

**Comment by ElePT** [comment]
aha, yes, I don't know how I read the changes the other way round (as removing `if typing.TYPE_CHECKING:` instead of adding). No comments then.

**Comment by kt474** [comment]
Can `PauliSumOp` be removed completely then?

**Comment by 1ucian0** [comment]
> Can PauliSumOp be removed completely then?

If you do, I think mypy will fail.

**Comment by kt474** [comment]
> > Can PauliSumOp be removed completely then?
> 
> If you do, I think mypy will fail.

I meant if it's being deprecated, will `PauliSumOp` still be an acceptable type for observables in `Estimator`? If it is, what would the appropriate import be?

**Comment by ElePT** [comment]
> I meant if it's being deprecated, will PauliSumOp still be an acceptable type for observables in Estimator? If it is, what would the appropriate import be?

@kt474 Maybe a bit more background: `PauliSumOp` was deprecated in qiskit 0.43 (not removed, but deprecated). When we deprecated it, we removed its internal use within the primitives, but we kept the user-facing typehint to respect the deprecation period of opflow (we wanted to give users some time to update their code) and for consistency with the base primitives (which respect the deprecation period of opflow). In other words, functionally, the typehint can be removed now and the code will work just fine, but interface-wise, we shouldn't remove it before the base primitives do it.  Why can we remove it easily?? Because its almost-direct replacement is `SparsePauliOp`, which:

1. is of type `BaseOperator` (already supported in the primitives)
2. is actually what is currently used in all of the code examples and internally maintained libraries that use the primitives

Does this make sense?

**Comment by kt474** [comment]
> Does this make sense?

Makes sense to me! Thanks for explaining

**Review by kt474 — APPROVED** [review]

**Pull request merged**
