### PR TITLE
Remove deprecation warning  for unsupported parameters of transpilation settings

### PR DESCRIPTION
**Pull request by merav-aharoni**
### Summary
Removed 1 deprecation warning for unsupported parameters of `transpilation settings`.

### Details and comments
Part of #784 .
Question - regarding `translation_method` and `timing_constraints`, do we want to raise an error or simply ignore? Because for other unsupported options, we simply ignore.

### CODE REVIEW

**Comment by kt474** [comment]
> Question - regarding translation_method and timing_constraints, do we want to raise an error or simply ignore? Because for other unsupported options, we simply ignore.

Since it's been more than 6 months, I think we can just ignore unsupported options

**Comment by merav-aharoni** [comment]
When checking the removal of deprecation warning, I noticed that if an unsupported option is passed, the server will return an error (possibly after a long time). So I added validation checks for level 2 options. We already have checks for level 1 and level 3.

**Review by kt474 — APPROVED** [review]

**Comment by jyu00** [comment]
We specifically allow kwargs in `Options` to allow people to test undocumented features. If you are going to raise, perhaps one can bypass that behavior using an env variable (I think there was one before, but maybe it's in qiskit-ibm-provider).

**Comment by merav-aharoni** [comment]
@jyu00 - Indeed there is an environment variable that controls whether to run _validate_options or not. So the user can turn set `QISKIT_RUNTIME_SKIP_OPTIONS_VALIDATION=False` to turn off all the validations.

**Pull request merged**
