### PR TITLE
remove decompose in Grover with sampler tutorial

### LINKED ISSUE #282: Remove decomposed circuits in Grover with sampler tutorials after UCRZ gate serialization bug fix
**What is the expected feature or enhancement?**

Grover circuits had to be decomposed 4 levels down to avoid QPY serialization bug when I was making the tutorial. This should be removed once the bug is fixed: https://github.com/Qiskit/qiskit-terra/issues/7847

https://github.com/Qiskit/qiskit-ibm-runtime/blame/main/docs/tutorials/grover_with_sampler.ipynb#L132-L144

**Acceptance criteria**

### PR DESCRIPTION
**Pull request by HuangJunye**
### Summary

Remove the additional `decompose()` in Grover with sampler tutorials added as a work around for a QPY serialization bug. The bug is [now fixed](https://github.com/Qiskit/qiskit-terra/pull/7933) in Terra 0.20.1 and the internal runtime provider was updated to use Qiskit Terra 0.20.1 as well.

### Details and comments
Fixes #282

### CODE REVIEW

**Review by rathishcholarajan — APPROVED** [review]
LGTM! Thanks @HuangJunye!

**Comment by HuangJunye** [comment]
@rathishcholarajan Thanks for the approval. Should we start the Docs Publish workflow?

**Comment by HuangJunye** [comment]
I can take care of that step but I want to know if there is any considerations of when you want to run the Docs Publish workflow. Should we trigger it whenever we have a doc related PR?

**Comment by rathishcholarajan** [comment]
I just started one, we haven't added any new features or bug fixes in code, so it is ok to deploy now. We need to make sure of this before deploying every time.

**Comment by HuangJunye** [comment]
What happens if there is changes in the code? Are you worried about the API reference for the unstable version being published?

**Pull request merged**
