### PR TITLE
Removed deprecated qiskit_ibm_runtime.IBMRuntimeService class

### LINKED ISSUE #359: Remove deprecate IBMRuntimeService class
**What is the expected feature or enhancement?**
IBMRuntimeService was deprecate and renamed to QiskitRuntimeService. [IBMRuntimeService](https://github.com/Qiskit/qiskit-ibm-runtime/blob/d199b83ef21fd24b8bec33ab04638a27ecd6f93c/qiskit_ibm_runtime/qiskit_runtime_service.py#L1418) class can now be removed.

### PR DESCRIPTION
**Pull request by bopardikarsoham**
I have removed the deprecated IBMRuntimeService class as per Issue https://github.com/Qiskit/qiskit-ibm-runtime/issues/359. This PR will be on hold as per the discussion in PR #363.

Fixes #359

### CODE REVIEW

**Review by rathishcholarajan — CHANGES_REQUESTED** [review]
@bopardikarsoham This class has to be removed https://github.com/Qiskit/qiskit-ibm-runtime/blob/6647f477209b92b97796671c223e25d4e4efb3ca/qiskit_ibm_runtime/qiskit_runtime_service.py#L1439 in this PR.

**Comment by bopardikarsoham** [comment]
> @bopardikarsoham This class has to be removed
> 
> https://github.com/Qiskit/qiskit-ibm-runtime/blob/6647f477209b92b97796671c223e25d4e4efb3ca/qiskit_ibm_runtime/qiskit_runtime_service.py#L1439
> 
> in this PR.

Ohh right I'll make the changes

**Comment by bopardikarsoham** [comment]
I have updated the PR @rathishcholarajan

**Review by rathishcholarajan — CHANGES_REQUESTED** [review]
@bopardikarsoham Could you pls remove IBMRuntimeService from this line as well https://github.com/Qiskit/qiskit-ibm-runtime/blob/315a088a844dc8aa4452bde6136b53694dfb3220/qiskit_ibm_runtime/__init__.py#L234 ?

**Comment by bopardikarsoham** [comment]
> @bopardikarsoham Could you pls remove IBMRuntimeService from this line as well
> 
> https://github.com/Qiskit/qiskit-ibm-runtime/blob/315a088a844dc8aa4452bde6136b53694dfb3220/qiskit_ibm_runtime/__init__.py#L234
> 
> ?

I had actually made a complete PR and removed all these lines perhaps a clash with my previous PRs have caused problems. I'll make a fresh PR for this issue

**Pull request closed without merging**
