### PR TITLE
Moving update_fake_backends.py from Qiskit

### PR DESCRIPTION
**Pull request by 1ucian0**
With the transition of fake backends from Qiskit to `qiskit-ibm-runtime`, I'm moving some of the tools that use to be there to keep the backends up to date. This PR brings https://github.com/Qiskit/qiskit/pull/8336

### CODE REVIEW

**Comment by ElePT** [comment]
Thanks for handling this move. I will make sure to include this tool in the `fake_provider` deprecations in Qiskit once this PR is merged.

**Comment by kt474** [comment]
@1ucian0 Is this PR ready for review? Does it still need to be in draft mode?

**Comment by 1ucian0** [comment]
Some testing is still needed and, seems it is not part of the release, I was going to give another push after the release season. Do you needed sooner? I can put some time on it this week.

**Comment by kt474** [comment]
> Some testing is still needed and, seems it is not part of the release, I was going to give another push after the release season. Do you needed sooner? I can put some time on it this week.

Nope, no rush, thanks for the update

**Comment by kt474** [comment]
This PR is 6 months old, is it ok to close for now and reopen if necessary?

**Comment by kt474** [comment]
Closing, feel free to reopen

**Pull request closed without merging**
